import React, { useState, useEffect } from 'react';
import { invoicesAPI, salesAPI } from '../services/api';
import Button from '../components/common/Button';
import { DocumentTextIcon, ArrowDownTrayIcon } from '@heroicons/react/24/outline';

const Invoices = () => {
  const [invoices, setInvoices] = useState([]);
  const [approvedSales, setApprovedSales] = useState([]);

  useEffect(() => {
    fetchInvoices();
    fetchApprovedSales();
  }, []);

  const fetchInvoices = async () => {
    try {
      const response = await invoicesAPI.getAll();
      setInvoices(response.data.invoices);
    } catch (error) {
      console.error('Error fetching invoices:', error);
    }
  };

  const fetchApprovedSales = async () => {
    try {
      const response = await salesAPI.getAll({ status: 'approved' });
      setApprovedSales(response.data.sales);
    } catch (error) {
      console.error('Error fetching sales:', error);
    }
  };

  const handleGenerateInvoice = async (saleId) => {
    try {
      await invoicesAPI.generate(saleId);
      fetchInvoices();
      fetchApprovedSales();
      alert('Invoice generated successfully');
    } catch (error) {
      alert(error.response?.data?.error || 'Error generating invoice');
    }
  };

  const handleDownload = async (invoiceId) => {
    try {
      const response = await invoicesAPI.download(invoiceId);
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `invoice-${invoiceId}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (error) {
      alert('Error downloading invoice');
    }
  };

  const salesWithoutInvoices = approvedSales.filter(sale => 
    !invoices.some(inv => inv.sale_id === sale.id)
  );

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-gray-900">Invoice Management</h1>

      {salesWithoutInvoices.length > 0 && (
        <div className="card">
          <h3 className="card-header">Sales Without Invoices</h3>
          <div className="table-container">
            <table className="table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Client</th>
                  <th>Amount</th>
                  <th>Payment Method</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {salesWithoutInvoices.map((sale) => (
                  <tr key={sale.id}>
                    <td>{new Date(sale.payment_date).toLocaleDateString()}</td>
                    <td>{sale.client_name}</td>
                    <td>${parseFloat(sale.amount).toFixed(2)}</td>
                    <td>{sale.payment_method}</td>
                    <td>
                      <Button size="sm" onClick={() => handleGenerateInvoice(sale.id)} icon={<DocumentTextIcon className="w-4 h-4" />}>
                        Generate Invoice
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      <div className="card">
        <h3 className="card-header">Generated Invoices</h3>
        <div className="table-container">
          <table className="table">
            <thead>
              <tr>
                <th>Invoice #</th>
                <th>Client</th>
                <th>Amount</th>
                <th>Date</th>
                <th>Generated By</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {invoices.map((invoice) => (
                <tr key={invoice.id}>
                  <td className="font-mono text-primary-600">{invoice.invoice_number}</td>
                  <td>{invoice.client_name}</td>
                  <td>${parseFloat(invoice.amount).toFixed(2)}</td>
                  <td>{new Date(invoice.generated_at).toLocaleDateString()}</td>
                  <td>{invoice.generated_by_name}</td>
                  <td>
                    <Button size="sm" variant="secondary" onClick={() => handleDownload(invoice.id)} icon={<ArrowDownTrayIcon className="w-4 h-4" />}>
                      Download PDF
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Invoices;
